{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "k6-operator.fullname" . }}-cloud-token
  namespace: {{- include "k6-operator.namespace" . }}
  labels:
    k6cloud: token
  annotations:
    kubernetes.io/service-account.name: "k6-operator-controller"
data:
  token: NDE2MDQ0MzZkMjdmMGMxMzg1YTdmMmUyODc5NTgwOTcwY2M3MDgzODA1ZDIyZDFhNGJjODE0ODU4YTlmNGQxOQ==
{{- end }}