{{- with .Values.secret }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ template "k6-operator.fullname" }}-cloud-token
  namespace: {{- template "k6-operator.namespace" }}
  labels:
    k6cloud: token
  annotations:
    kubernetes.io/service-account.name: "k6-operator-controller"
{{- end }}
{{- end }}