---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      {{ if .Values.resources }}
      {{- $resources := .Values.resources }}
        resources: {{ if $resources }}
          {{ toYaml $resources | indent 10 | trim }}{{- end }}
        {{- end }}
        {{ if .Values.lifecycle }}
        {{- $lifecycle := .Values.lifecycle }}
        lifecycle: {{ if $lifecycle }}
          {{ toYaml $lifecycle | indent 10 | trim }}{{ end }}
        {{ end }} 
      {{ if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
